const ARTIST_FLAGS = {
    "3 Doors Down": "🇺🇸",
    "A-ha": "🇳🇴",
    "Abracadabra": "🇦🇷",
    "Aerosmith": "🇺🇸",
    "Alberto Plaza": "🇨🇱",
    "Alejandro Fernandez": "🇲🇽",
    "Alejandro Filio": "🇲🇽",
    "Alejandro Sanz": "🇪🇸",
    "Almirante": "🇵🇦",
    "Ana Belen": "🇪🇸",
    "Andres Calamaro": "🇦🇷",
    "Autenticos Decadentes": "🇦🇷",
    "Bacilos": "🌎",
    "Banda Maguey": "🇲🇽",
    "Ben E King": "🇺🇸",
    "Bill Withers": "🇺🇸",
    "Billy Joel": "🇺🇸",
    "Bob Marley": "🇯🇲",
    "Bon Jovi": "🇺🇸",
    "Cafe Tacuba": "🇲🇽",
    "Caifanes": "🇲🇽",
    "Camilo Sesto": "🇪🇸",
    "Carin Leon": "🇲🇽",
    "Cesar Banana Pueyrredon": "🇦🇷",
    "Charly Garcia": "🇦🇷",
    "Christian Nodal": "🇲🇽",
    "Coldplay": "🇬🇧",
    "Creedence Clearwater Revival": "🇺🇸",
    "Cultura Profetica": "🇵🇷",
    "Diego Verdaguer": "🇦🇷",
    "Dread Mar I": "🇦🇷",
    "Duncan Dhu": "🇪🇸",
    "Dyango": "🇪🇸",
    "Eagles": "🇺🇸",
    "Elefante": "🇲🇽",
    "Emmanuel": "🇲🇽",
    "Enanitos Verdes": "🇦🇷",
    "Enrique Guzman": "🇲🇽",
    "Eric Clapton": "🇬🇧",
    "Extreme": "🇺🇸",
    "Facundo Cabral": "🇦🇷",
    "Frank Sinatra": "🇺🇸",
    "Gandhi": "🇨🇷",
    "Gaviota": "🇨🇷",
    "Gian Marco": "🇵🇪",
    "Gianluca Grignani": "🇮🇹",
    "Gondwana": "🇨🇱",
    "Goo Goo Dolls": "🇺🇸",
    "Guns N Roses": "🇺🇸",
    "Heroes del Silencio": "🇪🇸",
    "Hombres G": "🇪🇸",
    "Hoobastank": "🇺🇸",
    "Incubus": "🇺🇸",
    "Jaime Gamboa (Capmany)": "🇨🇷",
    "Jarabe de Palo": "🇪🇸",
    "Jessi Uribe": "🇨🇴",
    "Jessi Uribe y Galy Galeano": "🇨🇴",
    "Jimi Hendrix": "🇺🇸",
    "Joan Manuel Serrat": "🇪🇸",
    "Joan Sebastian": "🇲🇽",
    "Joaquin Sabina": "🇪🇸",
    "Joe Satriani": "🇺🇸",
    "John Denver": "🇺🇸",
    "John Fogerty": "🇺🇸",
    "John Lennon": "🇬🇧",
    "Jose Alfredo Jimenez": "🇲🇽",
    "Jose Domingo Figueroa": "🇻🇪",
    "Jose Feliciano": "🇵🇷",
    "Jose Luis Perales": "🇪🇸",
    "Jose Maria Napoleon": "🇲🇽",
    "Joseito Fernandez": "🇨🇺",
    "Julio Jaramillo": "🇪🇨",
    "Kadeho": "🇨🇷",
    "Ke Personajes": "🇦🇷",
    "La Sonora Santanera": "🇲🇽",
    "La Union": "🇪🇸",
    "Led Zeppelin": "🇬🇧",
    "Leo Dan": "🇦🇷",
    "Leonel Garcia": "🇲🇽",
    "Los Abuelos de la Nada": "🇦🇷",
    "Los Angeles Azules": "🇲🇽",
    "Los Bukis": "🇲🇽",
    "Los Caporales": "🇨🇷",
    "Los Choclok": "🇲🇽",
    "Los Panchos": "🇲🇽",
    "Los Prisioneros": "🇨🇱",
    "Los Tres Reyes": "🇲🇽",
    "Luis Alberto Spinetta": "🇦🇷",
    "Luis Eduardo Aute": "🇪🇸",
    "Luis Miguel": "🇲🇽",
    "Luis Miguel (Los Panchos)": "🇲🇽",
    "Mana": "🇲🇽",
    "Marc Anthony": "🇵🇷",
    "Marco Antonio Solis": "🇲🇽",
    "Metallica": "🇺🇸",
    "Miguel Gallardo": "🇪🇸",
    "Miguel Matamoros": "🇨🇺",
    "Miguel Rios": "🇪🇸",
    "Neil Young": "🇨🇦",
    "Nino Bravo": "🇪🇸",
    "Oasis": "🇬🇧",
    "Passenger": "🇬🇧",
    "Pearl Jam": "🇺🇸",
    "Pedro Fernandez": "🇲🇽",
    "Pedro Infante": "🇲🇽",
    "Pepe Aguilar": "🇲🇽",
    "Phantom Planet": "🇺🇸",
    "Pink Floyd": "🇬🇧",
    "Proyecto Uno": "🇩🇴",
    "Radiohead": "🇬🇧",
    "Red Hot Chili Peppers": "🇺🇸",
    "Reyli Barba": "🇲🇽",
    "Ricardo Arjona": "🇬🇹",
    "Ritchie Valens": "🇺🇸",
    "Roberto Carlos": "🇧🇷",
    "Sandro": "🇦🇷",
    "Santana": "🇲🇽",
    "Scorpions": "🇩🇪",
    "Sebastian Yatra": "🇨🇴",
    "Selena": "🇺🇸",
    "Silvio Rodriguez": "🇨🇺",
    "Slipknot": "🇺🇸",
    "Soda Stereo": "🇦🇷",
    "Sr Loop": "🇵🇦",
    "Sting": "🇬🇧",
    "Sui Generis": "🇦🇷",
    "Suite Doble": "🇨🇷",
    "Tango India": "🇨🇷",
    "The Calling": "🇺🇸",
    "The Doors": "🇺🇸",
    "The Police": "🇬🇧",
    "The Shadows": "🇬🇧",
    "The Verve": "🇬🇧",
    "Thirty Seconds to Mars": "🇺🇸",
    "Tradicional Costarricense": "🇨🇷",
    "Vicente Fernandez": "🇲🇽",
    "Victor Heredia": "🇦🇷",
    "Victor Manuelle": "🇵🇷",
    "Yahir": "🇲🇽"
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        ARTIST_FLAGS
    };
}
