// Shared song data for Catarsis Musical
// This data is used across multiple pages including the songbook and voting system

const SONGS = [
{
id: 1,
title: "La Gloria eres Tu",
artist: "Luis Miguel (Los Panchos)",
vibe: "boleros-del-recuerdo",
},
{
id: 2,
title: "Usted",
artist: "Luis Miguel (Los Panchos)",
vibe: "boleros-del-recuerdo",
},
{
id: 3,
title: "Escandalo",
artist: "Marc Anthony",
vibe: "boleros-del-recuerdo",
},
{
id: 4,
title: "Porque te tengo que olvidar",
artist: "Jose Feliciano",
vibe: "boleros-del-recuerdo",
},
{
id: 5,
title: "Hasta Ayer",
artist: "Marc Anthony",
vibe: "boleros-del-recuerdo",
},
{
id: 6,
title: "Perfume de Gardenias",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 7,
title: "Las Luces de Nueva York",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 8,
title: "Urge",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 9,
title: "Nuestro Juramento",
artist: "Julio Jaramillo",
vibe: "boleros-del-recuerdo",
},
{
id: 10,
title: "No me conoces",
artist: "Marc Anthony",
vibe: "boleros-del-recuerdo",
},
{
id: 11,
title: "La Copa Rota",
artist: "Jose Feliciano",
vibe: "boleros-del-recuerdo",
},
{
id: 12,
title: "Motivos",
artist: "Jose Domingo Figueroa",
vibe: "boleros-del-recuerdo",
},
{
id: 13,
title: "Lagrimas Negras",
artist: "Miguel Matamoros",
vibe: "boleros-del-recuerdo",
},
{
id: 14,
title: "Soy el ladron",
artist: "Diego Verdaguer",
vibe: "boleros-del-recuerdo",
},
{
id: 15,
title: "Historia de un amor",
artist: "Los Panchos",
vibe: "boleros-del-recuerdo",
},
{
id: 16,
title: "Este es un nuevo dia",
artist: "Facundo Cabral",
vibe: "trova-y-plancha",
},
{
id: 17,
title: "Quien fuera",
artist: "Silvio Rodriguez",
vibe: "trova-y-plancha",
},
{
id: 18,
title: "Brazos de sol",
artist: "Alejandro Filio",
vibe: "trova-y-plancha",
},
{
id: 19,
title: "Sin tu latido",
artist: "Luis Eduardo Aute",
vibe: "trova-y-plancha",
},
{
id: 20,
title: "Santa Lucia",
artist: "Miguel Rios",
vibe: "trova-y-plancha",
},
{
id: 21,
title: "Todo a pulmon",
artist: "Miguel Rios",
vibe: "trova-y-plancha",
},
{
id: 22,
title: "Aventurera",
artist: "Alberto Plaza",
vibe: "trova-y-plancha",
},
{
id: 23,
title: "Corazon Partio",
artist: "Alejandro Sanz",
vibe: "trova-y-plancha",
},
{
id: 24,
title: "El Hombre del Piano",
artist: "Billy Joel",
vibe: "trova-y-plancha",
},
{
id: 25,
title: "Solo pienso en ti",
artist: "Victor Manuelle",
vibe: "trova-y-plancha",
},
{
id: 26,
title: "Te Conozco",
artist: "Ricardo Arjona",
vibe: "trova-y-plancha",
},
{
id: 27,
title: "La Historia del Taxi",
artist: "Ricardo Arjona",
vibe: "trova-y-plancha",
},
{
id: 28,
title: "Libre",
artist: "Nino Bravo",
vibe: "trova-y-plancha",
},
{
id: 29,
title: "Y nos dieron las 10",
artist: "Joaquin Sabina",
vibe: "trova-y-plancha",
},
{
id: 30,
title: "Por el boulevard de los suenios rotos",
artist: "Joaquin Sabina",
vibe: "trova-y-plancha",
},
{
id: 31,
title: "19 dias y 500 noches",
artist: "Joaquin Sabina",
vibe: "trova-y-plancha",
},
{
id: 32,
title: "Dime que puedo hacer sin ti",
artist: "Suite Doble",
vibe: "trova-y-plancha",
},
{
id: 33,
title: "Cancion para mi muerte",
artist: "Sui Generis",
vibe: "trova-y-plancha",
},
{
id: 34,
title: "Confesiones de invierno",
artist: "Sui Generis",
vibe: "trova-y-plancha",
},
{
id: 35,
title: "Aquellas pequenas cosas",
artist: "Joan Manuel Serrat",
vibe: "trova-y-plancha",
},
{
id: 36,
title: "Sobreviviendo",
artist: "Victor Heredia",
vibe: "trova-y-plancha",
},
{
id: 37,
title: "Cancion para Annie",
artist: "John Denver",
vibe: "clasicos-romanticos",
},
{
id: 38,
title: "Que vas a hacer esta noche",
artist: "Gaviota",
vibe: "clasicos-romanticos",
},
{
id: 39,
title: "Quedate",
artist: "Abracadabra",
vibe: "clasicos-romanticos",
},
{
id: 40,
title: "Quieres ser mi amante",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 41,
title: "Mi credo",
artist: "Pepe Aguilar",
vibe: "clasicos-romanticos",
},
{
id: 42,
title: "Disename",
artist: "Joan Sebastian",
vibe: "clasicos-romanticos",
},
{
id: 43,
title: "Puerto Limon",
artist: "Abracadabra",
vibe: "clasicos-romanticos",
},
{
id: 44,
title: "Y como es el",
artist: "Jose Luis Perales",
vibe: "clasicos-romanticos",
},
{
id: 45,
title: "La venia bendita",
artist: "Marco Antonio Solis",
vibe: "clasicos-romanticos",
},
{
id: 46,
title: "Cartas amarillas",
artist: "Nino Bravo",
vibe: "clasicos-romanticos",
},
{
id: 47,
title: "Vive",
artist: "Jose Maria Napoleon",
vibe: "clasicos-romanticos",
},
{
id: 48,
title: "Derroche",
artist: "Ana Belen",
vibe: "clasicos-romanticos",
},
{
id: 49,
title: "Eso y mas",
artist: "Joan Sebastian",
vibe: "clasicos-romanticos",
},
{
id: 50,
title: "Te quiero te quiero",
artist: "Nino Bravo",
vibe: "clasicos-romanticos",
},
{
id: 51,
title: "Despues de ti",
artist: "Jose Feliciano",
vibe: "clasicos-romanticos",
},
{
id: 52,
title: "Piel de angel",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 53,
title: "Perdoname",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 54,
title: "Algo de mi",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 55,
title: "El amor de mi vida",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 56,
title: "Un velero llamado libertad",
artist: "Jose Luis Perales",
vibe: "clasicos-romanticos",
},
{
id: 57,
title: "No te apartes de mi",
artist: "Yahir",
vibe: "clasicos-romanticos",
},
{
id: 58,
title: "Para empezar",
artist: "Leonel Garcia",
vibe: "clasicos-romanticos",
},
{
id: 59,
title: "Mi historia entre tus dedos",
artist: "Gianluca Grignani",
vibe: "clasicos-romanticos",
},
{
id: 60,
title: "Mary es mi amor",
artist: "Leo Dan",
vibe: "clasicos-romanticos",
},
{
id: 61,
title: "Que pasara manana",
artist: "Jose Luis Perales",
vibe: "clasicos-romanticos",
},
{
id: 62,
title: "Pajarillo",
artist: "Jose Maria Napoleon",
vibe: "clasicos-romanticos",
},
{
id: 63,
title: "Adonde vas amor",
artist: "Dyango",
vibe: "clasicos-romanticos",
},
{
id: 64,
title: "Un beso y una flor",
artist: "Nino Bravo",
vibe: "clasicos-romanticos",
},
{
id: 65,
title: "Por ese palpitar",
artist: "Sandro",
vibe: "clasicos-romanticos",
},
{
id: 66,
title: "Hoy tengo ganas de ti",
artist: "Miguel Gallardo",
vibe: "clasicos-romanticos",
},
{
id: 67,
title: "Mi chica de humo",
artist: "Emmanuel",
vibe: "rock-latino",
},
{
id: 68,
title: "Afuera",
artist: "Caifanes",
vibe: "rock-latino",
},
{
id: 69,
title: "Voy a pasarmelo bien",
artist: "Hombres G",
vibe: "rock-latino",
},
{
id: 70,
title: "Golpes en el corazon",
artist: "Autenticos Decadentes",
vibe: "rock-latino",
},
{
id: 71,
title: "El lado oscuro",
artist: "Jarabe de Palo",
vibe: "rock-latino",
},
{
id: 72,
title: "Mil horas",
artist: "Los Abuelos de la Nada",
vibe: "rock-latino",
},
{
id: 73,
title: "Amores lejanos",
artist: "Enanitos Verdes",
vibe: "rock-latino",
},
{
id: 74,
title: "Mi primer dia sin ti",
artist: "Enanitos Verdes",
vibe: "rock-latino",
},
{
id: 75,
title: "Si no te hubieras ido",
artist: "Mana",
vibe: "rock-latino",
},
{
id: 76,
title: "De la noche a la manana",
artist: "Elefante",
vibe: "rock-latino",
},
{
id: 77,
title: "Ojos marrones",
artist: "Sebastian Yatra",
vibe: "rock-latino",
},
{
id: 78,
title: "Guitarras blancas",
artist: "Enanitos Verdes",
vibe: "rock-latino",
},
{
id: 79,
title: "La ciudad de la furia",
artist: "Soda Stereo",
vibe: "rock-latino",
},
{
id: 80,
title: "Tren al sur",
artist: "Los Prisioneros",
vibe: "rock-latino",
},
{
id: 81,
title: "Asi es la vida",
artist: "Elefante",
vibe: "rock-latino",
},
{
id: 82,
title: "La flaca",
artist: "Jarabe de Palo",
vibe: "rock-latino",
},
{
id: 83,
title: "Flaca",
artist: "Andres Calamaro",
vibe: "rock-latino",
},
{
id: 84,
title: "Sola",
artist: "Kadeho",
vibe: "rock-latino",
},
{
id: 85,
title: "Caraluna",
artist: "Bacilos",
vibe: "rock-latino",
},
{
id: 86,
title: "Lamento boliviano",
artist: "Enanitos Verdes",
vibe: "rock-latino",
},
{
id: 87,
title: "Lobo hombre en Paris",
artist: "La Union",
vibe: "rock-latino",
},
{
id: 88,
title: "En algun lugar",
artist: "Duncan Dhu",
vibe: "rock-latino",
},
{
id: 89,
title: "Eres",
artist: "Cafe Tacuba",
vibe: "rock-latino",
},
{
id: 90,
title: "De musica ligera",
artist: "Soda Stereo",
vibe: "rock-latino",
},
{
id: 91,
title: "Maldito duende",
artist: "Heroes del Silencio",
vibe: "rock-latino",
},
{
id: 92,
title: "Otro gol",
artist: "Gandhi",
vibe: "rock-latino",
},
{
id: 93,
title: "Azul",
artist: "Tango India",
vibe: "rock-latino",
},
{
id: 94,
title: "No voy en tren",
artist: "Charly Garcia",
vibe: "rock-latino",
},
{
id: 95,
title: "Agua",
artist: "Jarabe de Palo",
vibe: "rock-latino",
},
{
id: 96,
title: "Muchacha ojos de papel",
artist: "Luis Alberto Spinetta",
vibe: "rock-latino",
},
{
id: 97,
title: "Corazon",
artist: "Autenticos Decadentes",
vibe: "rock-latino",
},
{
id: 98,
title: "Besandote",
artist: "Autenticos Decadentes",
vibe: "rock-latino",
},
{
id: 99,
title: "La modelo",
artist: "Jaime Gamboa (Capmany)",
vibe: "serenata-despecho",
},
{
id: 100,
title: "La simeona",
artist: "Los Caporales",
vibe: "serenata-despecho",
},
{
id: 101,
title: "Tears in Heaven",
artist: "Eric Clapton",
vibe: "classical-rock",
},
{
id: 102,
title: "Green River",
artist: "Creedence Clearwater Revival",
vibe: "classical-rock",
},
{
id: 103,
title: "The Old Man Down the Road",
artist: "John Fogerty",
vibe: "classical-rock",
},
{
id: 104,
title: "Black Magic Woman",
artist: "Santana",
vibe: "classical-rock",
},
{
id: 105,
title: "Little Wing",
artist: "Jimi Hendrix",
vibe: "classical-rock",
},
{
id: 106,
title: "Surfing with the Alien",
artist: "Joe Satriani",
vibe: "classical-rock",
},
{
id: 107,
title: "My Way",
artist: "Frank Sinatra",
vibe: "classical-rock",
},
{
id: 108,
title: "Take On Me",
artist: "A-ha",
vibe: "classical-rock",
},
{
id: 109,
title: "Wind of Change",
artist: "Scorpions",
vibe: "classical-rock",
},
{
id: 110,
title: "Apache",
artist: "The Shadows",
vibe: "classical-rock",
},
{
id: 111,
title: "Riders on the Storm",
artist: "The Doors",
vibe: "classical-rock",
},
{
id: 112,
title: "Every Breath You Take",
artist: "The Police",
vibe: "classical-rock",
},
{
id: 113,
title: "Have You Ever Seen the Rain",
artist: "Creedence Clearwater Revival",
vibe: "classical-rock",
},
{
id: 114,
title: "Wish You Were Here",
artist: "Pink Floyd",
vibe: "classical-rock",
},
{
id: 115,
title: "Dream On",
artist: "Aerosmith",
vibe: "classical-rock",
},
{
id: 116,
title: "Stairway to Heaven",
artist: "Led Zeppelin",
vibe: "classical-rock",
},
{
id: 117,
title: "Babe Im Gonna Leave You",
artist: "Led Zeppelin",
vibe: "classical-rock",
},
{
id: 118,
title: "Hotel California",
artist: "Eagles",
vibe: "classical-rock",
},
{
id: 119,
title: "Wonderwall",
artist: "Oasis",
vibe: "classical-rock",
},
{
id: 120,
title: "Creep",
artist: "Radiohead",
vibe: "classical-rock",
},
{
id: 121,
title: "Under the Bridge",
artist: "Red Hot Chili Peppers",
vibe: "classical-rock",
},
{
id: 122,
title: "Patience",
artist: "Guns N Roses",
vibe: "classical-rock",
},
{
id: 123,
title: "More Than Words",
artist: "Extreme",
vibe: "classical-rock",
},
{
id: 124,
title: "Iris",
artist: "Goo Goo Dolls",
vibe: "classical-rock",
},
{
id: 125,
title: "Fix You",
artist: "Coldplay",
vibe: "classical-rock",
},
{
id: 126,
title: "Black",
artist: "Pearl Jam",
vibe: "classical-rock",
},
{
id: 127,
title: "Yellow Ledbetter",
artist: "Pearl Jam",
vibe: "classical-rock",
},
{
id: 128,
title: "Here Without You",
artist: "3 Doors Down",
vibe: "classical-rock",
},
{
id: 129,
title: "The Reason",
artist: "Hoobastank",
vibe: "classical-rock",
},
{
id: 130,
title: "Drive",
artist: "Incubus",
vibe: "classical-rock",
},
{
id: 131,
title: "Bittersweet Symphony",
artist: "The Verve",
vibe: "classical-rock",
},
{
id: 132,
title: "Old Man",
artist: "Neil Young",
vibe: "classical-rock",
},
{
id: 133,
title: "California",
artist: "Phantom Planet",
vibe: "classical-rock",
},
{
id: 134,
title: "Vermilion pt 2",
artist: "Slipknot",
vibe: "classical-rock",
},
{
id: 135,
title: "Englishman in New York",
artist: "Sting",
vibe: "classical-rock",
},
{
id: 136,
title: "From Yesterday",
artist: "Thirty Seconds to Mars",
vibe: "classical-rock",
},
{
id: 137,
title: "Aint No Sunshine",
artist: "Bill Withers",
vibe: "classical-rock",
},
{
id: 138,
title: "Mama Said",
artist: "Metallica",
vibe: "classical-rock",
},
{
id: 139,
title: "Nothing Else Matters",
artist: "Metallica",
vibe: "classical-rock",
},
{
id: 140,
title: "For Whom the Bell Tolls",
artist: "Metallica",
vibe: "classical-rock",
},
{
id: 141,
title: "The Day That Never Comes",
artist: "Metallica",
vibe: "classical-rock",
},
{
id: 142,
title: "You Give Love a Bad Name",
artist: "Bon Jovi",
vibe: "classical-rock",
},
{
id: 143,
title: "Let Her Go",
artist: "Passenger",
vibe: "classical-rock",
},
{
id: 144,
title: "Wherever You Will Go",
artist: "The Calling",
vibe: "classical-rock",
},
{
id: 145,
title: "Imagine",
artist: "John Lennon",
vibe: "classical-rock",
},
{
id: 146,
title: "Stand by Me",
artist: "Ben E King",
vibe: "classical-rock",
},
{
id: 147,
title: "Quien es usted",
artist: "Christian Nodal",
vibe: "banda-popular",
},
{
id: 148,
title: "Vivo en el 6",
artist: "Christian Nodal",
vibe: "banda-popular",
},
{
id: 149,
title: "La primera cita",
artist: "Carin Leon",
vibe: "banda-popular",
},
{
id: 150,
title: "Dulce pecado",
artist: "Jessi Uribe",
vibe: "banda-popular",
},
{
id: 151,
title: "Si una vez",
artist: "Selena",
vibe: "banda-popular",
},
{
id: 152,
title: "Caballero",
artist: "Alejandro Fernandez",
vibe: "banda-popular",
},
{
id: 153,
title: "Por mujeres como tu",
artist: "Pepe Aguilar",
vibe: "banda-popular",
},
{
id: 154,
title: "Amarte a la antigua",
artist: "Pedro Fernandez",
vibe: "banda-popular",
},
{
id: 155,
title: "Tu carcel",
artist: "Los Bukis",
vibe: "banda-popular",
},
{
id: 156,
title: "Tu eterno enamorado",
artist: "Banda Maguey",
vibe: "banda-popular",
},
{
id: 157,
title: "La cita",
artist: "Jessi Uribe y Galy Galeano",
vibe: "banda-popular",
},
{
id: 158,
title: "Tu",
artist: "Carin Leon",
vibe: "banda-popular",
},
{
id: 159,
title: "Hay que noche tan preciosa",
artist: "Pedro Infante",
vibe: "banda-popular",
},
{
id: 160,
title: "Enganada",
artist: "Los Tres Reyes",
vibe: "musica-de-trio",
},
{
id: 161,
title: "Odiame",
artist: "Los Tres Reyes",
vibe: "musica-de-trio",
},
{
id: 162,
title: "Hablame",
artist: "Los Panchos",
vibe: "musica-de-trio",
},
{
id: 163,
title: "Tres regalos",
artist: "Los Panchos",
vibe: "musica-de-trio",
},
{
id: 164,
title: "Sin un amor",
artist: "Los Panchos",
vibe: "musica-de-trio",
},
{
id: 165,
title: "Caminemos",
artist: "Los Panchos",
vibe: "musica-de-trio",
},
{
id: 166,
title: "Tu eres mi hermano del alma",
artist: "Roberto Carlos",
vibe: "musica-de-trio",
},
{
id: 167,
title: "Mujeres divinas",
artist: "Vicente Fernandez",
vibe: "musica-de-trio",
},
{
id: 168,
title: "Si nos dejan",
artist: "Jose Alfredo Jimenez",
vibe: "musica-de-trio",
},
{
id: 169,
title: "Perdon",
artist: "Los Panchos",
vibe: "musica-de-trio",
},
{
id: 170,
title: "Para estar",
artist: "Cultura Profetica",
vibe: "reggae-roots",
},
{
id: 171,
title: "Asi fue",
artist: "Dread Mar I",
vibe: "reggae-roots",
},
{
id: 172,
title: "Bonita",
artist: "Los Choclok",
vibe: "reggae-roots",
},
{
id: 173,
title: "No Woman No Cry",
artist: "Bob Marley",
vibe: "reggae-roots",
},
{
id: 174,
title: "Redemption Song",
artist: "Bob Marley",
vibe: "reggae-roots",
},
{
id: 175,
title: "Felicidad",
artist: "Gondwana",
vibe: "reggae-roots",
},
{
id: 176,
title: "Tu sin mi",
artist: "Dread Mar I",
vibe: "reggae-roots",
},
{
id: 177,
title: "Solo por ti",
artist: "Cultura Profetica",
vibe: "reggae-roots",
},
{
id: 178,
title: "Arbol sin hojas",
artist: "Dread Mar I",
vibe: "reggae-roots",
},
{
id: 179,
title: "Ella",
artist: "Almirante",
vibe: "reggae-roots",
},
{
id: 180,
title: "Pobre corazon",
artist: "Ke Personajes",
vibe: "cumbias",
},
{
id: 181,
title: "Adios amor / Oye mujer",
artist: "Ke Personajes",
vibe: "cumbias",
},
{
id: 182,
title: "Hoy",
artist: "Gian Marco",
vibe: "cumbias",
},
{
id: 183,
title: "Como la flor",
artist: "Selena",
vibe: "cumbias",
},
{
id: 184,
title: "El liston de tu pelo",
artist: "Los Angeles Azules",
vibe: "cumbias",
},
{
id: 185,
title: "Flor palida",
artist: "Marc Anthony",
vibe: "salsa",
},
{
id: 186,
title: "Tengo ganas",
artist: "Victor Manuelle",
vibe: "salsa",
},
{
id: 187,
title: "La Bamba",
artist: "Ritchie Valens",
vibe: "charangas",
},
{
id: 188,
title: "Voy a pasarmelo bien",
artist: "Hombres G",
vibe: "charangas",
},
{
id: 189,
title: "Guantanamera",
artist: "Joseito Fernandez",
vibe: "charangas",
},
{
id: 190,
title: "El Rey Tiburon",
artist: "Proyecto Uno",
vibe: "charangas",
},
{
id: 191,
title: "La luna y el toro",
artist: "Dyango",
vibe: "charangas",
},
{
id: 192,
title: "Amor del bueno",
artist: "Reyli Barba",
vibe: "extras-acusticos",
},
{
id: 193,
title: "No puedo enamorarme de ti",
artist: "Joaquin Sabina",
vibe: "extras-acusticos",
},
{
id: 194,
title: "Conociendote",
artist: "Cesar Banana Pueyrredon",
vibe: "extras-acusticos",
},
{
id: 195,
title: "Por ese palpitar",
artist: "Sandro",
vibe: "extras-acusticos",
},
{
id: 196,
title: "Sobreviviendo",
artist: "Victor Heredia",
vibe: "extras-acusticos",
},
{
id: 197,
title: "De la cana se hace el guaro",
artist: "Tradicional Costarricense",
vibe: "extras-acusticos",
},
{
id: 198,
title: "Popotitos",
artist: "Enrique Guzman",
vibe: "extras-acusticos",
},
{
id: 199,
title: "Azul",
artist: "Tango India",
vibe: "extras-acusticos",
},
{
id: 200,
title: "Otro gol",
artist: "Gandhi",
vibe: "extras-acusticos",
},
{
id: 201,
title: "Chao carino chao",
artist: "Abracadabra",
vibe: "extras-acusticos",
},
{
id: 202,
title: "Insensato",
artist: "Sr Loop",
vibe: "extras-acusticos",
},
{
id: 203,
title: "Eterna soledad",
artist: "Enanitos Verdes",
vibe: "extras-acusticos",
},
{
id: 204,
title: "Ojos marrones",
artist: "Sebastian Yatra",
vibe: "extras-acusticos",
},
{
id: 205,
title: "Tu sin mi",
artist: "Dread Mar I",
vibe: "extras-acusticos",
},
{
id: 206,
title: "Solo por ti",
artist: "Cultura Profetica",
vibe: "extras-acusticos",
},
{
id: 207,
title: "Arbol sin hojas",
artist: "Dread Mar I",
vibe: "extras-acusticos",
},
{
id: 208,
title: "Ella",
artist: "Almirante",
vibe: "extras-acusticos",
},
{
id: 209,
title: "La luna y el toro",
artist: "Dyango",
vibe: "extras-acusticos",
},
{
id: 210,
title: "El Rey Tiburon",
artist: "Proyecto Uno",
vibe: "extras-acusticos",
},
{
id: 211,
title: "Guantanamera",
artist: "Joseito Fernandez",
vibe: "extras-acusticos",
},
{
id: 212,
title: "Besandote",
artist: "Autenticos Decadentes",
vibe: "extras-acusticos",
},
{
id: 213,
title: "Perfume de Gardenias",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 214,
title: "Las Luces de Nueva York",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 215,
title: "Escandalo",
artist: "Marc Anthony",
vibe: "boleros-del-recuerdo",
},
{
id: 216,
title: "Urge",
artist: "La Sonora Santanera",
vibe: "boleros-del-recuerdo",
},
{
id: 217,
title: "La modelo",
artist: "Jaime Gamboa (Capmany)",
vibe: "serenata-despecho",
},
{
id: 218,
title: "La simeona",
artist: "Los Caporales",
vibe: "serenata-despecho",
},
{
id: 219,
title: "Amarte es un placer",
artist: "Luis Miguel",
vibe: "clasicos-romanticos",
},
{
id: 220,
title: "Te quiero te quiero",
artist: "Nino Bravo",
vibe: "clasicos-romanticos",
},
{
id: 221,
title: "Un beso y una flor",
artist: "Nino Bravo",
vibe: "clasicos-romanticos",
},
{
id: 222,
title: "Algo de mi",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 223,
title: "Perdoname",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 224,
title: "El amor de mi vida",
artist: "Camilo Sesto",
vibe: "clasicos-romanticos",
},
{
id: 225,
title: "Y como es el",
artist: "Jose Luis Perales",
vibe: "clasicos-romanticos",
},
{
id: 226,
title: "Mi credo",
artist: "Pepe Aguilar",
vibe: "clasicos-romanticos",
},
{
id: 227,
title: "Disename",
artist: "Joan Sebastian",
vibe: "clasicos-romanticos",
},
{
id: 228,
title: "Vive",
artist: "Jose Maria Napoleon",
vibe: "clasicos-romanticos",
},
{
id: 229,
title: "Enganada",
artist: "Los Tres Reyes",
vibe: "serenata-despecho",
},
{
id: 230,
title: "Odiame",
artist: "Los Tres Reyes",
vibe: "serenata-despecho",
},
{
id: 231,
title: "Para empezar",
artist: "Leonel Garcia",
vibe: "clasicos-romanticos",
},
{
id: 232,
title: "Mi historia entre tus dedos",
artist: "Gianluca Grignani",
vibe: "clasicos-romanticos",
},
{
id: 233,
title: "Mary es mi amor",
artist: "Leo Dan",
vibe: "clasicos-romanticos",
},
{
id: 234,
title: "Que pasara manana",
artist: "Jose Luis Perales",
vibe: "clasicos-romanticos",
},
{
id: 235,
title: "Adonde vas amor",
artist: "Dyango",
vibe: "clasicos-romanticos",
}
];